version: "3"
services:
  node_react_builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FOLDER: $FOLDER
    ports:
      - 85:80
    restart: unless-stopped
    container_name: react_builder
